version: 2

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "monthly"
      target-branch: "develop"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "monthly"
        day: "sunday"
      target-branch: "develop"
      commit-message:
        prefix: "npm"
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
        interval: "monthly"
      target-branch: "develop"
