export const testData = {
  items: [
    {
      album: {
        album_type: 'compilation',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/1LZEQNv7sE11VDY3SdxQeN',
            },
            href: 'https://api.spotify.com/v1/artists/1LZEQNv7sE11VDY3SdxQeN',
            id: '1LZEQNv7sE11VDY3SdxQeN',
            name: 'Bee Gees',
            type: 'artist',
            uri: 'spotify:artist:1LZEQNv7sE11VDY3SdxQeN',
          },
        ],
        available_markets: [
          'AR',
          'AU',
          'AT',
          'BE',
          'BO',
          'BR',
          'BG',
          'CA',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DK',
          'DO',
          'DE',
          'EC',
          'EE',
          'SV',
          'FI',
          'FR',
          'GR',
          'GT',
          'HN',
          'HK',
          'HU',
          'IS',
          'IE',
          'IT',
          'LV',
          'LT',
          'LU',
          'MY',
          'MT',
          'MX',
          'NL',
          'NZ',
          'NI',
          'NO',
          'PA',
          'PY',
          'PE',
          'PH',
          'PL',
          'PT',
          'SG',
          'SK',
          'ES',
          'SE',
          'CH',
          'TW',
          'TR',
          'UY',
          'US',
          'GB',
          'AD',
          'LI',
          'MC',
          'ID',
          'JP',
          'TH',
          'VN',
          'RO',
          'IL',
          'ZA',
          'SA',
          'AE',
          'BH',
          'QA',
          'OM',
          'KW',
          'EG',
          'MA',
          'DZ',
          'TN',
          'LB',
          'JO',
          'PS',
          'IN',
          'BY',
          'KZ',
          'MD',
          'UA',
          'AL',
          'BA',
          'HR',
          'ME',
          'MK',
          'RS',
          'SI',
          'KR',
          'BD',
          'PK',
          'LK',
          'GH',
          'KE',
          'NG',
          'TZ',
          'UG',
          'AG',
          'AM',
          'BS',
          'BB',
          'BZ',
          'BT',
          'BW',
          'BF',
          'CV',
          'CW',
          'DM',
          'FJ',
          'GM',
          'GE',
          'GD',
          'GW',
          'GY',
          'HT',
          'JM',
          'KI',
          'LS',
          'LR',
          'MW',
          'MV',
          'ML',
          'MH',
          'FM',
          'NA',
          'NR',
          'NE',
          'PW',
          'PG',
          'WS',
          'SM',
          'ST',
          'SN',
          'SC',
          'SL',
          'SB',
          'KN',
          'LC',
          'VC',
          'SR',
          'TL',
          'TO',
          'TT',
          'TV',
          'VU',
          'AZ',
          'BN',
          'BI',
          'KH',
          'CM',
          'TD',
          'KM',
          'GQ',
          'SZ',
          'GA',
          'GN',
          'KG',
          'LA',
          'MO',
          'MR',
          'MN',
          'NP',
          'RW',
          'TG',
          'UZ',
          'ZW',
          'BJ',
          'MG',
          'MU',
          'MZ',
          'AO',
          'CI',
          'DJ',
          'ZM',
          'CD',
          'CG',
          'IQ',
          'LY',
          'TJ',
          'VE',
          'ET',
          'XK',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5YHZaCxCuuK81h4Fimb9rT',
        },
        href: 'https://api.spotify.com/v1/albums/5YHZaCxCuuK81h4Fimb9rT',
        id: '5YHZaCxCuuK81h4Fimb9rT',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b27352038992fc6d7868f31d23b7',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e0252038992fc6d7868f31d23b7',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d0000485152038992fc6d7868f31d23b7',
            width: 64,
          },
        ],
        is_playable: true,
        name: 'Greatest',
        release_date: '1979-01-01',
        release_date_precision: 'day',
        total_tracks: 27,
        type: 'album',
        uri: 'spotify:album:5YHZaCxCuuK81h4Fimb9rT',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/1LZEQNv7sE11VDY3SdxQeN',
          },
          href: 'https://api.spotify.com/v1/artists/1LZEQNv7sE11VDY3SdxQeN',
          id: '1LZEQNv7sE11VDY3SdxQeN',
          name: 'Bee Gees',
          type: 'artist',
          uri: 'spotify:artist:1LZEQNv7sE11VDY3SdxQeN',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
        'AM',
        'BS',
        'BB',
        'BZ',
        'BT',
        'BW',
        'BF',
        'CV',
        'CW',
        'DM',
        'FJ',
        'GM',
        'GE',
        'GD',
        'GW',
        'GY',
        'HT',
        'JM',
        'KI',
        'LS',
        'LR',
        'MW',
        'MV',
        'ML',
        'MH',
        'FM',
        'NA',
        'NR',
        'NE',
        'PW',
        'PG',
        'WS',
        'SM',
        'ST',
        'SN',
        'SC',
        'SL',
        'SB',
        'KN',
        'LC',
        'VC',
        'SR',
        'TL',
        'TO',
        'TT',
        'TV',
        'VU',
        'AZ',
        'BN',
        'BI',
        'KH',
        'CM',
        'TD',
        'KM',
        'GQ',
        'SZ',
        'GA',
        'GN',
        'KG',
        'LA',
        'MO',
        'MR',
        'MN',
        'NP',
        'RW',
        'TG',
        'UZ',
        'ZW',
        'BJ',
        'MG',
        'MU',
        'MZ',
        'AO',
        'CI',
        'DJ',
        'ZM',
        'CD',
        'CG',
        'IQ',
        'LY',
        'TJ',
        'VE',
        'ET',
        'XK',
      ],
      disc_number: 1,
      duration_ms: 245200,
      explicit: false,
      external_ids: {
        isrc: 'GBAKW7701005',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/2JoZzpdeP2G6Csfdq5aLXP',
      },
      href: 'https://api.spotify.com/v1/tracks/2JoZzpdeP2G6Csfdq5aLXP',
      id: '2JoZzpdeP2G6Csfdq5aLXP',
      is_local: false,
      is_playable: true,
      name: 'How Deep Is Your Love',
      popularity: 82,
      preview_url: null,
      track_number: 6,
      type: 'track',
      uri: 'spotify:track:2JoZzpdeP2G6Csfdq5aLXP',
    },
    {
      album: {
        album_type: 'single',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4fjnGkj0w54KWyIk2VTW7B',
            },
            href: 'https://api.spotify.com/v1/artists/4fjnGkj0w54KWyIk2VTW7B',
            id: '4fjnGkj0w54KWyIk2VTW7B',
            name: 'Lee Ji Hye',
            type: 'artist',
            uri: 'spotify:artist:4fjnGkj0w54KWyIk2VTW7B',
          },
        ],
        available_markets: [
          'AR',
          'AU',
          'AT',
          'BE',
          'BO',
          'BR',
          'BG',
          'CA',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DK',
          'DO',
          'DE',
          'EC',
          'EE',
          'SV',
          'FI',
          'FR',
          'GR',
          'GT',
          'HN',
          'HK',
          'HU',
          'IS',
          'IE',
          'IT',
          'LV',
          'LT',
          'LU',
          'MY',
          'MT',
          'MX',
          'NL',
          'NZ',
          'NI',
          'NO',
          'PA',
          'PY',
          'PE',
          'PH',
          'PL',
          'PT',
          'SG',
          'SK',
          'ES',
          'SE',
          'CH',
          'TW',
          'TR',
          'UY',
          'US',
          'GB',
          'AD',
          'LI',
          'MC',
          'ID',
          'JP',
          'TH',
          'VN',
          'RO',
          'IL',
          'ZA',
          'SA',
          'AE',
          'BH',
          'QA',
          'OM',
          'KW',
          'EG',
          'MA',
          'DZ',
          'TN',
          'LB',
          'JO',
          'PS',
          'IN',
          'BY',
          'KZ',
          'MD',
          'UA',
          'AL',
          'BA',
          'HR',
          'ME',
          'MK',
          'RS',
          'SI',
          'KR',
          'BD',
          'PK',
          'LK',
          'GH',
          'KE',
          'NG',
          'TZ',
          'UG',
          'AG',
          'AM',
          'BS',
          'BB',
          'BZ',
          'BT',
          'BW',
          'BF',
          'CV',
          'CW',
          'DM',
          'FJ',
          'GM',
          'GE',
          'GD',
          'GW',
          'GY',
          'HT',
          'JM',
          'KI',
          'LS',
          'LR',
          'MW',
          'MV',
          'ML',
          'MH',
          'FM',
          'NA',
          'NR',
          'NE',
          'PW',
          'PG',
          'PR',
          'WS',
          'SM',
          'ST',
          'SN',
          'SC',
          'SL',
          'SB',
          'KN',
          'LC',
          'VC',
          'SR',
          'TL',
          'TO',
          'TT',
          'TV',
          'VU',
          'AZ',
          'BN',
          'BI',
          'KH',
          'CM',
          'TD',
          'KM',
          'GQ',
          'SZ',
          'GA',
          'GN',
          'KG',
          'LA',
          'MO',
          'MR',
          'MN',
          'NP',
          'RW',
          'TG',
          'UZ',
          'ZW',
          'BJ',
          'MG',
          'MU',
          'MZ',
          'AO',
          'CI',
          'DJ',
          'ZM',
          'CD',
          'CG',
          'IQ',
          'LY',
          'TJ',
          'VE',
          'ET',
          'XK',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/37bm94EQ6BcYDiwHNBKU0l',
        },
        href: 'https://api.spotify.com/v1/albums/37bm94EQ6BcYDiwHNBKU0l',
        id: '37bm94EQ6BcYDiwHNBKU0l',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b273c008bfb64fbd56e4ce29685b',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e02c008bfb64fbd56e4ce29685b',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d00004851c008bfb64fbd56e4ce29685b',
            width: 64,
          },
        ],
        is_playable: true,
        name: 'Love Me Love Me',
        release_date: '2014-11-21',
        release_date_precision: 'day',
        total_tracks: 3,
        type: 'album',
        uri: 'spotify:album:37bm94EQ6BcYDiwHNBKU0l',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4fjnGkj0w54KWyIk2VTW7B',
          },
          href: 'https://api.spotify.com/v1/artists/4fjnGkj0w54KWyIk2VTW7B',
          id: '4fjnGkj0w54KWyIk2VTW7B',
          name: 'Lee Ji Hye',
          type: 'artist',
          uri: 'spotify:artist:4fjnGkj0w54KWyIk2VTW7B',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
        'AM',
        'BS',
        'BB',
        'BZ',
        'BT',
        'BW',
        'BF',
        'CV',
        'CW',
        'DM',
        'FJ',
        'GM',
        'GE',
        'GD',
        'GW',
        'GY',
        'HT',
        'JM',
        'KI',
        'LS',
        'LR',
        'MW',
        'MV',
        'ML',
        'MH',
        'FM',
        'NA',
        'NR',
        'NE',
        'PW',
        'PG',
        'PR',
        'WS',
        'SM',
        'ST',
        'SN',
        'SC',
        'SL',
        'SB',
        'KN',
        'LC',
        'VC',
        'SR',
        'TL',
        'TO',
        'TT',
        'TV',
        'VU',
        'AZ',
        'BN',
        'BI',
        'KH',
        'CM',
        'TD',
        'KM',
        'GQ',
        'SZ',
        'GA',
        'GN',
        'KG',
        'LA',
        'MO',
        'MR',
        'MN',
        'NP',
        'RW',
        'TG',
        'UZ',
        'ZW',
        'BJ',
        'MG',
        'MU',
        'MZ',
        'AO',
        'CI',
        'DJ',
        'ZM',
        'CD',
        'CG',
        'IQ',
        'LY',
        'TJ',
        'VE',
        'ET',
        'XK',
      ],
      disc_number: 1,
      duration_ms: 189080,
      explicit: false,
      external_ids: {
        isrc: 'KRA341453783',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/4azXF9x6zXgRbdDbVg4iPu',
      },
      href: 'https://api.spotify.com/v1/tracks/4azXF9x6zXgRbdDbVg4iPu',
      id: '4azXF9x6zXgRbdDbVg4iPu',
      is_local: false,
      is_playable: true,
      name: 'Love Me Love Me - Remix Version',
      popularity: 29,
      preview_url: null,
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:4azXF9x6zXgRbdDbVg4iPu',
    },
    {
      album: {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5wVJpXzuKV6Xj7Yhsf2uYx',
            },
            href: 'https://api.spotify.com/v1/artists/5wVJpXzuKV6Xj7Yhsf2uYx',
            id: '5wVJpXzuKV6Xj7Yhsf2uYx',
            name: 'HANRORO',
            type: 'artist',
            uri: 'spotify:artist:5wVJpXzuKV6Xj7Yhsf2uYx',
          },
        ],
        available_markets: [
          'AR',
          'AU',
          'AT',
          'BE',
          'BO',
          'BR',
          'BG',
          'CA',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DK',
          'DO',
          'DE',
          'EC',
          'EE',
          'SV',
          'FI',
          'FR',
          'GR',
          'GT',
          'HN',
          'HK',
          'HU',
          'IS',
          'IE',
          'IT',
          'LV',
          'LT',
          'LU',
          'MY',
          'MT',
          'MX',
          'NL',
          'NZ',
          'NI',
          'NO',
          'PA',
          'PY',
          'PE',
          'PH',
          'PL',
          'PT',
          'SG',
          'SK',
          'ES',
          'SE',
          'CH',
          'TW',
          'TR',
          'UY',
          'US',
          'GB',
          'AD',
          'LI',
          'MC',
          'ID',
          'JP',
          'TH',
          'VN',
          'RO',
          'IL',
          'ZA',
          'SA',
          'AE',
          'BH',
          'QA',
          'OM',
          'KW',
          'EG',
          'MA',
          'DZ',
          'TN',
          'LB',
          'JO',
          'PS',
          'IN',
          'BY',
          'KZ',
          'MD',
          'UA',
          'AL',
          'BA',
          'HR',
          'ME',
          'MK',
          'RS',
          'SI',
          'KR',
          'BD',
          'PK',
          'LK',
          'GH',
          'KE',
          'NG',
          'TZ',
          'UG',
          'AG',
          'AM',
          'BS',
          'BB',
          'BZ',
          'BT',
          'BW',
          'BF',
          'CV',
          'CW',
          'DM',
          'FJ',
          'GM',
          'GE',
          'GD',
          'GW',
          'GY',
          'HT',
          'JM',
          'KI',
          'LS',
          'LR',
          'MW',
          'MV',
          'ML',
          'MH',
          'FM',
          'NA',
          'NR',
          'NE',
          'PW',
          'PG',
          'PR',
          'WS',
          'SM',
          'ST',
          'SN',
          'SC',
          'SL',
          'SB',
          'KN',
          'LC',
          'VC',
          'SR',
          'TL',
          'TO',
          'TT',
          'TV',
          'VU',
          'AZ',
          'BN',
          'BI',
          'KH',
          'CM',
          'TD',
          'KM',
          'GQ',
          'SZ',
          'GA',
          'GN',
          'KG',
          'LA',
          'MO',
          'MR',
          'MN',
          'NP',
          'RW',
          'TG',
          'UZ',
          'ZW',
          'BJ',
          'MG',
          'MU',
          'MZ',
          'AO',
          'CI',
          'DJ',
          'ZM',
          'CD',
          'CG',
          'IQ',
          'LY',
          'TJ',
          'VE',
          'ET',
          'XK',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/2DV7iVJ7L5DRQijgjyqLyQ',
        },
        href: 'https://api.spotify.com/v1/albums/2DV7iVJ7L5DRQijgjyqLyQ',
        id: '2DV7iVJ7L5DRQijgjyqLyQ',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b273afda752d5db59e06d3f86e3b',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e02afda752d5db59e06d3f86e3b',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d00004851afda752d5db59e06d3f86e3b',
            width: 64,
          },
        ],
        is_playable: true,
        name: 'JAMONG SALGU CLUB',
        release_date: '2025-08-04',
        release_date_precision: 'day',
        total_tracks: 7,
        type: 'album',
        uri: 'spotify:album:2DV7iVJ7L5DRQijgjyqLyQ',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/5wVJpXzuKV6Xj7Yhsf2uYx',
          },
          href: 'https://api.spotify.com/v1/artists/5wVJpXzuKV6Xj7Yhsf2uYx',
          id: '5wVJpXzuKV6Xj7Yhsf2uYx',
          name: 'HANRORO',
          type: 'artist',
          uri: 'spotify:artist:5wVJpXzuKV6Xj7Yhsf2uYx',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
        'AM',
        'BS',
        'BB',
        'BZ',
        'BT',
        'BW',
        'BF',
        'CV',
        'CW',
        'DM',
        'FJ',
        'GM',
        'GE',
        'GD',
        'GW',
        'GY',
        'HT',
        'JM',
        'KI',
        'LS',
        'LR',
        'MW',
        'MV',
        'ML',
        'MH',
        'FM',
        'NA',
        'NR',
        'NE',
        'PW',
        'PG',
        'PR',
        'WS',
        'SM',
        'ST',
        'SN',
        'SC',
        'SL',
        'SB',
        'KN',
        'LC',
        'VC',
        'SR',
        'TL',
        'TO',
        'TT',
        'TV',
        'VU',
        'AZ',
        'BN',
        'BI',
        'KH',
        'CM',
        'TD',
        'KM',
        'GQ',
        'SZ',
        'GA',
        'GN',
        'KG',
        'LA',
        'MO',
        'MR',
        'MN',
        'NP',
        'RW',
        'TG',
        'UZ',
        'ZW',
        'BJ',
        'MG',
        'MU',
        'MZ',
        'AO',
        'CI',
        'DJ',
        'ZM',
        'CD',
        'CG',
        'IQ',
        'LY',
        'TJ',
        'VE',
        'ET',
        'XK',
      ],
      disc_number: 1,
      duration_ms: 192000,
      explicit: false,
      external_ids: {
        isrc: 'KRMIM2540757',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/3sOAwRg5esaxDcWnUigWPv',
      },
      href: 'https://api.spotify.com/v1/tracks/3sOAwRg5esaxDcWnUigWPv',
      id: '3sOAwRg5esaxDcWnUigWPv',
      is_local: false,
      is_playable: true,
      name: '0+0',
      popularity: 70,
      preview_url: null,
      track_number: 4,
      type: 'track',
      uri: 'spotify:track:3sOAwRg5esaxDcWnUigWPv',
    },
    {
      album: {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2WPn0emjr8XPmMOT0bBcPe',
            },
            href: 'https://api.spotify.com/v1/artists/2WPn0emjr8XPmMOT0bBcPe',
            id: '2WPn0emjr8XPmMOT0bBcPe',
            name: 'Piero Piccioni',
            type: 'artist',
            uri: 'spotify:artist:2WPn0emjr8XPmMOT0bBcPe',
          },
        ],
        available_markets: [
          'AR',
          'AU',
          'AT',
          'BE',
          'BO',
          'BR',
          'BG',
          'CA',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DK',
          'DO',
          'DE',
          'EC',
          'EE',
          'SV',
          'FI',
          'FR',
          'GR',
          'GT',
          'HN',
          'HK',
          'HU',
          'IS',
          'IE',
          'IT',
          'LV',
          'LT',
          'LU',
          'MY',
          'MT',
          'MX',
          'NL',
          'NZ',
          'NI',
          'NO',
          'PA',
          'PY',
          'PE',
          'PH',
          'PL',
          'PT',
          'SG',
          'SK',
          'ES',
          'SE',
          'CH',
          'TW',
          'TR',
          'UY',
          'US',
          'GB',
          'AD',
          'LI',
          'MC',
          'ID',
          'JP',
          'TH',
          'VN',
          'RO',
          'IL',
          'ZA',
          'SA',
          'AE',
          'BH',
          'QA',
          'OM',
          'KW',
          'EG',
          'MA',
          'DZ',
          'TN',
          'LB',
          'JO',
          'PS',
          'IN',
          'BY',
          'KZ',
          'MD',
          'UA',
          'AL',
          'BA',
          'HR',
          'ME',
          'MK',
          'RS',
          'SI',
          'KR',
          'BD',
          'PK',
          'LK',
          'GH',
          'KE',
          'NG',
          'TZ',
          'UG',
          'AG',
          'AM',
          'BS',
          'BB',
          'BZ',
          'BT',
          'BW',
          'BF',
          'CV',
          'CW',
          'DM',
          'FJ',
          'GM',
          'GE',
          'GD',
          'GW',
          'GY',
          'HT',
          'JM',
          'KI',
          'LS',
          'LR',
          'MW',
          'MV',
          'ML',
          'MH',
          'FM',
          'NA',
          'NR',
          'NE',
          'PW',
          'PG',
          'PR',
          'WS',
          'SM',
          'ST',
          'SN',
          'SC',
          'SL',
          'SB',
          'KN',
          'LC',
          'VC',
          'SR',
          'TL',
          'TO',
          'TT',
          'TV',
          'VU',
          'AZ',
          'BN',
          'BI',
          'KH',
          'CM',
          'TD',
          'KM',
          'GQ',
          'SZ',
          'GA',
          'GN',
          'KG',
          'LA',
          'MO',
          'MR',
          'MN',
          'NP',
          'RW',
          'TG',
          'UZ',
          'ZW',
          'BJ',
          'MG',
          'MU',
          'MZ',
          'AO',
          'CI',
          'DJ',
          'ZM',
          'CD',
          'CG',
          'IQ',
          'LY',
          'TJ',
          'VE',
          'ET',
          'XK',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/4krilUTGX55iq61zRxhBhg',
        },
        href: 'https://api.spotify.com/v1/albums/4krilUTGX55iq61zRxhBhg',
        id: '4krilUTGX55iq61zRxhBhg',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b273c7fd2701f2c979e17ad29db3',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e02c7fd2701f2c979e17ad29db3',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d00004851c7fd2701f2c979e17ad29db3',
            width: 64,
          },
        ],
        is_playable: true,
        name: 'Romantica - Vintage Italian Soundtracks',
        release_date: '2026-02-09',
        release_date_precision: 'day',
        total_tracks: 30,
        type: 'album',
        uri: 'spotify:album:4krilUTGX55iq61zRxhBhg',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2WPn0emjr8XPmMOT0bBcPe',
          },
          href: 'https://api.spotify.com/v1/artists/2WPn0emjr8XPmMOT0bBcPe',
          id: '2WPn0emjr8XPmMOT0bBcPe',
          name: 'Piero Piccioni',
          type: 'artist',
          uri: 'spotify:artist:2WPn0emjr8XPmMOT0bBcPe',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
        'AM',
        'BS',
        'BB',
        'BZ',
        'BT',
        'BW',
        'BF',
        'CV',
        'CW',
        'DM',
        'FJ',
        'GM',
        'GE',
        'GD',
        'GW',
        'GY',
        'HT',
        'JM',
        'KI',
        'LS',
        'LR',
        'MW',
        'MV',
        'ML',
        'MH',
        'FM',
        'NA',
        'NR',
        'NE',
        'PW',
        'PG',
        'PR',
        'WS',
        'SM',
        'ST',
        'SN',
        'SC',
        'SL',
        'SB',
        'KN',
        'LC',
        'VC',
        'SR',
        'TL',
        'TO',
        'TT',
        'TV',
        'VU',
        'AZ',
        'BN',
        'BI',
        'KH',
        'CM',
        'TD',
        'KM',
        'GQ',
        'SZ',
        'GA',
        'GN',
        'KG',
        'LA',
        'MO',
        'MR',
        'MN',
        'NP',
        'RW',
        'TG',
        'UZ',
        'ZW',
        'BJ',
        'MG',
        'MU',
        'MZ',
        'AO',
        'CI',
        'DJ',
        'ZM',
        'CD',
        'CG',
        'IQ',
        'LY',
        'TJ',
        'VE',
        'ET',
        'XK',
      ],
      disc_number: 1,
      duration_ms: 41396,
      explicit: false,
      external_ids: {
        isrc: 'ITD060901835',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/4cfJ3aGJewVPdfaV5tYgnX',
      },
      href: 'https://api.spotify.com/v1/tracks/4cfJ3aGJewVPdfaV5tYgnX',
      id: '4cfJ3aGJewVPdfaV5tYgnX',
      is_local: false,
      is_playable: true,
      name: 'Le streghe - Waltz',
      popularity: 17,
      preview_url: null,
      track_number: 28,
      type: 'track',
      uri: 'spotify:track:4cfJ3aGJewVPdfaV5tYgnX',
    },
    {
      album: {
        album_type: 'album',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/3rxeQlsv0Sc2nyYaZ5W71T',
            },
            href: 'https://api.spotify.com/v1/artists/3rxeQlsv0Sc2nyYaZ5W71T',
            id: '3rxeQlsv0Sc2nyYaZ5W71T',
            name: 'Chet Baker',
            type: 'artist',
            uri: 'spotify:artist:3rxeQlsv0Sc2nyYaZ5W71T',
          },
        ],
        available_markets: [
          'AR',
          'AU',
          'AT',
          'BE',
          'BO',
          'BR',
          'BG',
          'CA',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DK',
          'DO',
          'DE',
          'EC',
          'EE',
          'SV',
          'FI',
          'FR',
          'GR',
          'GT',
          'HN',
          'HK',
          'HU',
          'IS',
          'IE',
          'IT',
          'LV',
          'LT',
          'LU',
          'MY',
          'MT',
          'MX',
          'NL',
          'NZ',
          'NI',
          'NO',
          'PA',
          'PY',
          'PE',
          'PH',
          'PL',
          'PT',
          'SG',
          'SK',
          'ES',
          'SE',
          'CH',
          'TW',
          'TR',
          'UY',
          'US',
          'GB',
          'AD',
          'LI',
          'MC',
          'ID',
          'JP',
          'TH',
          'VN',
          'RO',
          'IL',
          'ZA',
          'SA',
          'AE',
          'BH',
          'QA',
          'OM',
          'KW',
          'EG',
          'MA',
          'DZ',
          'TN',
          'LB',
          'JO',
          'PS',
          'IN',
          'BY',
          'KZ',
          'MD',
          'UA',
          'AL',
          'BA',
          'HR',
          'ME',
          'MK',
          'RS',
          'SI',
          'KR',
          'BD',
          'PK',
          'LK',
          'GH',
          'KE',
          'NG',
          'TZ',
          'UG',
          'AG',
          'AM',
          'BS',
          'BB',
          'BZ',
          'BT',
          'BW',
          'BF',
          'CV',
          'CW',
          'DM',
          'FJ',
          'GM',
          'GE',
          'GD',
          'GW',
          'GY',
          'HT',
          'JM',
          'KI',
          'LS',
          'LR',
          'MW',
          'MV',
          'ML',
          'MH',
          'FM',
          'NA',
          'NR',
          'NE',
          'PW',
          'PG',
          'WS',
          'SM',
          'ST',
          'SN',
          'SC',
          'SL',
          'SB',
          'KN',
          'LC',
          'VC',
          'SR',
          'TL',
          'TO',
          'TT',
          'TV',
          'VU',
          'AZ',
          'BN',
          'BI',
          'KH',
          'CM',
          'TD',
          'KM',
          'GQ',
          'SZ',
          'GA',
          'GN',
          'KG',
          'LA',
          'MO',
          'MR',
          'MN',
          'NP',
          'RW',
          'TG',
          'UZ',
          'ZW',
          'BJ',
          'MG',
          'MU',
          'MZ',
          'AO',
          'CI',
          'DJ',
          'ZM',
          'CD',
          'CG',
          'IQ',
          'LY',
          'TJ',
          'VE',
          'ET',
          'XK',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/6NVtIIsVMTuphtcAN9FxCc',
        },
        href: 'https://api.spotify.com/v1/albums/6NVtIIsVMTuphtcAN9FxCc',
        id: '6NVtIIsVMTuphtcAN9FxCc',
        images: [
          {
            height: 640,
            url: 'https://i.scdn.co/image/ab67616d0000b273139959676bd3da09a14b40c3',
            width: 640,
          },
          {
            height: 300,
            url: 'https://i.scdn.co/image/ab67616d00001e02139959676bd3da09a14b40c3',
            width: 300,
          },
          {
            height: 64,
            url: 'https://i.scdn.co/image/ab67616d00004851139959676bd3da09a14b40c3',
            width: 64,
          },
        ],
        is_playable: true,
        name: 'Chet Baker Sings And Plays (Remastered 2004)',
        release_date: '1955-01-01',
        release_date_precision: 'day',
        total_tracks: 11,
        type: 'album',
        uri: 'spotify:album:6NVtIIsVMTuphtcAN9FxCc',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/3rxeQlsv0Sc2nyYaZ5W71T',
          },
          href: 'https://api.spotify.com/v1/artists/3rxeQlsv0Sc2nyYaZ5W71T',
          id: '3rxeQlsv0Sc2nyYaZ5W71T',
          name: 'Chet Baker',
          type: 'artist',
          uri: 'spotify:artist:3rxeQlsv0Sc2nyYaZ5W71T',
        },
      ],
      available_markets: [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
        'JP',
        'TH',
        'VN',
        'RO',
        'IL',
        'ZA',
        'SA',
        'AE',
        'BH',
        'QA',
        'OM',
        'KW',
        'EG',
        'MA',
        'DZ',
        'TN',
        'LB',
        'JO',
        'PS',
        'IN',
        'BY',
        'KZ',
        'MD',
        'UA',
        'AL',
        'BA',
        'HR',
        'ME',
        'MK',
        'RS',
        'SI',
        'KR',
        'BD',
        'PK',
        'LK',
        'GH',
        'KE',
        'NG',
        'TZ',
        'UG',
        'AG',
        'AM',
        'BS',
        'BB',
        'BZ',
        'BT',
        'BW',
        'BF',
        'CV',
        'CW',
        'DM',
        'FJ',
        'GM',
        'GE',
        'GD',
        'GW',
        'GY',
        'HT',
        'JM',
        'KI',
        'LS',
        'LR',
        'MW',
        'MV',
        'ML',
        'MH',
        'FM',
        'NA',
        'NR',
        'NE',
        'PW',
        'PG',
        'WS',
        'SM',
        'ST',
        'SN',
        'SC',
        'SL',
        'SB',
        'KN',
        'LC',
        'VC',
        'SR',
        'TL',
        'TO',
        'TT',
        'TV',
        'VU',
        'AZ',
        'BN',
        'BI',
        'KH',
        'CM',
        'TD',
        'KM',
        'GQ',
        'SZ',
        'GA',
        'GN',
        'KG',
        'LA',
        'MO',
        'MR',
        'MN',
        'NP',
        'RW',
        'TG',
        'UZ',
        'ZW',
        'BJ',
        'MG',
        'MU',
        'MZ',
        'AO',
        'CI',
        'DJ',
        'ZM',
        'CD',
        'CG',
        'IQ',
        'LY',
        'TJ',
        'VE',
        'ET',
        'XK',
      ],
      disc_number: 1,
      duration_ms: 223706,
      explicit: false,
      external_ids: {
        isrc: 'USBN28900080',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/0UZFhlhUMrYyzzyOHkylM3',
      },
      href: 'https://api.spotify.com/v1/tracks/0UZFhlhUMrYyzzyOHkylM3',
      id: '0UZFhlhUMrYyzzyOHkylM3',
      is_local: false,
      is_playable: true,
      name: "Let's Get Lost",
      popularity: 56,
      preview_url: null,
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:0UZFhlhUMrYyzzyOHkylM3',
    },
  ],
  total: 751,
  limit: 5,
  offset: 5,
  href: 'https://api.spotify.com/v1/me/top/tracks?offset=5&limit=5&time_range=short_term&locale=en-SG,en;q%3D0.9,ko-KR;q%3D0.8,ko;q%3D0.7,zh-CN;q%3D0.6,zh;q%3D0.5,en-GB;q%3D0.4,en-US;q%3D0.3',
  next: 'https://api.spotify.com/v1/me/top/tracks?offset=10&limit=5&time_range=short_term&locale=en-SG,en;q%3D0.9,ko-KR;q%3D0.8,ko;q%3D0.7,zh-CN;q%3D0.6,zh;q%3D0.5,en-GB;q%3D0.4,en-US;q%3D0.3',
  previous:
    'https://api.spotify.com/v1/me/top/tracks?offset=0&limit=5&time_range=short_term&locale=en-SG,en;q%3D0.9,ko-KR;q%3D0.8,ko;q%3D0.7,zh-CN;q%3D0.6,zh;q%3D0.5,en-GB;q%3D0.4,en-US;q%3D0.3',
};
