name: Deployment AWS Amplify (PROD)
concurrency:
    group: prod
    cancel-in-progress: true
on:
    push:
        branches: [ master ]
jobs:
    install_build:
        env:
            CI: true
            REACT_APP_MODE: PRODUCTION
            MONGO_URI: ${{ secrets.MONGO_URI }}
            MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 20.18 ]
        steps:
            - name: Setup Node JS
              uses: actions/setup-node@v3.5.0
              with:
                node-version: ${{ matrix.node-version }}
                registry-url: 'https://registry.npmjs.org'
            - name: Get Latest Source Code
              uses: actions/checkout@v5.0.0
              with:
                submodules: recursive
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: NPM & Build
              run: npm i && npm run build
    deployment:
        if: "! contains(github.event.head_commit.message, '[skip_ci]')"
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Deploy to AWS Amplify (PROD)
              run: |
                URL="${{ secrets.AWS_WEBHOOK_PROD }}"
                curl -X POST -d {} "$URL" -H "Content-Type: application/json"
