name: Deploy to AWS Amplify (PROD)
on:
    push:
        branches: [ master ]
jobs:
    install_build:
        env:
            CI: true
            REACT_APP_MODE: PRODUCTION
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 20.18 ]
        steps:
            - name: Deploy to AWS Amplify
              run: |
                URL="${{ secrets.AWS_WEBHOOK_PROD }}"
                curl -X POST -d {} "$URL" -H "Content-Type: application/json"
